In [ ]:
# Tensorflow & Keras -> google
# Pytorch -> facebook

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
print(torch.__version__)

2.4.1+cu121


# Introduction to Vectors

In [ ]:
# scalar

In [ ]:
scalar = torch.tensor(7)
scalar

# scalar means single values
# vector means has magnitude and direction

tensor(7)

In [ ]:
# scalar
scalar.ndim

0

# vector

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
# change vector
vector.shape

torch.Size([2])

# matrix

In [ ]:
matrix=torch.tensor([[7,8],
                     [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

# access matrix elements

In [ ]:
matrix[0]

tensor([7, 8])

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
# mycode1)
matrix[0][0]

tensor(7)

In [ ]:
# mycode2)
matrix[0][1]

tensor(8)

# tensor

In [ ]:
tensor=tensor=torch.tensor([[[1,2,3],
                              [2,3,5],
                              [5,6,7]]])
tensor

tensor([[[1, 2, 3],
         [2, 3, 5],
         [5, 6, 7]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.0223, 0.1689, 0.2939, 0.5185],
        [0.6977, 0.8000, 0.1610, 0.2823],
        [0.6816, 0.9152, 0.3971, 0.8742]])

In [ ]:
# mycode using seed
#<--------------------->
torch.manual_seed(0)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]])

In [ ]:
torch.rand(3,3)

tensor([[0.6083, 0.2757, 0.4033],
        [0.2220, 0.2699, 0.2367],
        [0.2254, 0.3736, 0.5241]])

In [ ]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.ndim

2

In [ ]:
torch.range(0,10)

<ipython-input-54-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# 4 oct 2024

In [ ]:
import torch

In [ ]:
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Manipulation Tensors

In [ ]:
# Addition
# Subtraction
# Multiplication(element wise)
# Division

# It is similar to numpy

In [ ]:
tensor=torch.tensor([1,2,3])

In [ ]:
tensor([11, 12, 13])

tensor([10, 20, 30])

In [ ]:
tensor*10

tensor([10, 20, 30])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

# Matrix multipication

In [ ]:
# Inner dimensions must match:
# (3,2) @ (3,2)-- Wont Work
# (3,2) @ (2,3)-- Will work
# (2,3) @ (3,2)-- Will work

In [ ]:
# torch.matmul(torch.rand(3,2),torch.rand(3,2))

# it shows error

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

# //matmul means -> matrix multiplication

# //   m1xn1 and m2xn2
  #  //inner dimension should be same --> n1 and m2

tensor([[0.3706, 0.3337],
        [1.0148, 0.8124]])

# Tensor Aggregate(max,min,sum,mean etc)

In [ ]:
# Create a tensor
x=torch.arange(0,100,10)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x)

tensor(0)

In [ ]:
x.min()

tensor(0)

In [ ]:
#Find the max
torch.max(x)

tensor(90)

In [ ]:
x.max()

tensor(90)

In [ ]:
# Find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
# Find the Sum
torch.sum(x)

tensor(450)

In [ ]:
x.sum()

tensor(450)

# Finding the positional min & max

In [ ]:
# argmin gives the index of minimul value
x.argmin()

tensor(0)

In [ ]:
# argmax gives the index of maximum value
x.argmax()

tensor(9)

In [ ]:
x[9] # index

tensor(90)