# TensorFlow 2.0 Tutorial

![](https://blog.paperspace.com/content/images/size/w1050/2021/01/0_szgpfwmBY_CuZwP8-2.png)

In [ ]:
# shortcuts for collab
# ctrl + shift + Tab -> change chrome tabs.
# to show documentation -> ctrl + space or ctrl + shift + space

# 1) TensorFlow 2.0 Tutorial Introduction part - 1

# .....................Agenda

In [ ]:
# • What is TensorFlow?
# • Application # //so we understand that what we can build using tensorflow
# • Who can learn? #// can software deveoloper, android developer or web developer
# • Prerequisite
# • Dependency
# • Installation
# • Importing # // and then practical codes
# • Study materials # video me to hm sikhenge hi. isi ke sath hme official documents kha se milenge,
#                     aur hme shi treke se acha guidance kha se milega iske bare me bhi hm age chl chlke bat krenge in study materials.

# ....................What is TensorFlow?

In [ ]:
# TensorFlow is the core open source library to help you develop and
       # train Machine Learning/Deep Learning models.

# Develop by Google Brain Team

# TensorFlow is written in Python,C++,CUDA

# Platform: Linux, macOS, Windows, Android, JavaScript

# Initial release: November 9, 2015.

# explanation:
# 1st point ->  //Means ml and dl model ko train krte hai design krte hai and software ki pipeline ko complete krte hai.

# 3rd point -> Tensort flow is made in Python, C++, CUDA.
# CUDA becoz we use tensorflow GPU also.
# to agr hme gpu ka use ache se krna hai, to hme CUDA language ka bhi istemal krna pdega.
# but hm CUDA ko directly use nhi krenge. Hm jb tensorflow ka use krenge to tensorflow
# CUDA ka istemal krega. so that we can utilize GPU power efficiently(means ache se).
# to train and design ml model.

# 4th Platform means where we can run tensorflow code. to wha javascript hai.
# is means we can also run its code where js run



# Note: TensorFLow is a python library and also a framework of ml and dl. (from chatgpt)

# ....................Application

In [ ]:
# 1. Face recoginition application -> using computer vision
# 2. Self Driving Car/Autonomous vehicle -> using AI
# 3. Alexa -> using NLP [Natural Language Processing]
     # In NLP we interact with machine in our language and machine all interact with us in our language.
# 4. Robotics -> In robotics we can automate many works. so there we can also use TensorFlow.

# And,  There are thousands of applications where tensorflow is used.
# We can create/build application of different different domains using tensorflow library like aggriculture domain, healthcare,
# finance and education etc.

# ....................Who can learn?

In [ ]:
# • Python Developer
# • Machine Learning Engineer
# • Data Scientist
# • Artificial Intelligence Engineer
# • Deep learning Engineer
# • Computer Vision / Natural language procession Engineer

# If we want to go in these fields then we should know tensorflow.

# ....................Why TensorFlow?

In [ ]:
# Why learn TensorFlow?
# and is there any other library available in the market instead of tensorflow.
# if available then why we learn tensorflow?

# see below google trends and tensorflow vs pytorch.

# ....................//Google Trends

In [ ]:
# Google Trends pe jake hm tools ka comparision kr skte hai like TensorFlow and PyTorch.
#<---------------------------------------------------------------------------------------->

# > GUI of Google Trends
#<----------------------------->
     # search items           + compare

     # Location    Past day    All categories  Web Search

# > Now we have to compare TensorFlow and PyTorch, so we will customize GUI :
     # TensorFlow          PyTorch        + Add comparision

     # Worldwide       Past 5 years     All categories       Web Search

# ....................//TensorFlow Vs PyTorch

In [ ]:
# 1) TensorFlow and PyTorch is both competitor to each other.
#    Pytorch is created by facebook.

# 2) we can use both libraries to design and train ml model.

# 3) TensorFlow released 1st and then pytorch.

# 4) kuch year pehle tensorflow ka market research bhut bda tha.
#    and pytorch ko just reseach and developemnt ke liye use kiya jata tha.
#    But in today's time facebook team is more focus on pytorch.
#    and due to it. pytorch ka istemal krke jb bhi hm model ko design and train krte hai to hm model ko easily production me leke ja skte hai.
#    for ex: dectron.
#            dectron is a very powerful framework that we can used to solve computer vision problems.

# 5)  Agr hm google trend pe abhi line graph dekhenge to dono ka ration bhut close hai.
#     to hm ache se ni bta skte ki future me kiska use jada hoga.
#     bcoz dono ke developer team bhut ache hai. google and facebook.

# 6)  So we will use both jha tensorflow ki accuracy and speed jada hogi jis model me
    # hm wha tensorflow ka use krenge. and jha pytorch best hoga hm wha iska use krenge.

# ....................//About Pytorch

In [ ]:
# PyTorch is a deep learning framework developed by Facebook's AI Research lab (FAIR).
# It was released in 2016 and open sourced on GitHub in 2017.


# ....................//From Documentation

In [ ]:
# TensorFlow official website -> TensorFlow.org -> here we can read documentations.

# but is playlist me bhi hme use documentation se hindi me pdhenge.


# Why TensorFlow
#<------------------>

# Easy model building
# Robust Ml production anywhere -> we can deploy/run its code many os even android.
# Powerful experimetation for research


# Solutions to common ML problems
#<----------------------------------->

# simple step-by-step walkthroughts to solve common ML problems with TensorFlow.
        # Beginner                    Intermediate                   Expert
# 1) your first neural network    2) Recoomender systems     3) Generative adversarial networks



# Powered by TensorFlow
#<-------------------------->

# TensorFlow team also created videos on tensorflow on youtube in english.
# search tensorflow official.



# Companies using TensorFlow
#<------------------------------>


# airbnb    cocacola     DeepMind      GE Healthcare     Google   intel    NeRSC     Twitter

# News & announcements
#<------------------------->
# We can see all the latest information, blogs and news about tensorflow on tensorflow.org

# ....................Prerequisites

In [ ]:
# Prerequisites/Dependency for TensorFlow

# Python        Pandas
# Numpy         Matplotlib and seaborn
# Scipy         Maths:Matrix,Vector


# Note: Pyton and Numpy ata hai tb tb bhi hm tensorflow pdh skte hai.
# scipy not mandatory if numpy known

# Maths:Matrix,Vector : agr sirf understanding ke liye pdhna hai to  maths, vector in sbki need ni hai.
# but deep me pdhna hai to ye sn aana chahiye.
# and maths, statistics, probabiliy, matrix, vector, and calculus bhi ana chahiye.
# if we enter in the AI field.

# ....................Installation of TensorFlow

In [ ]:
# 1st create environment -> To create virtual environment install anaconda.

#                  pip install tensorflow     <- for cpu version
#                  pip install tensorflow-gpu <- for gpu version [gpu nvidia + support cuda]

# gpu wala code tb use krna hai jb hmara laptop nvidia ka gpu hoga, and wo CUDA ko support krta hai.
# yha jo tensorflow install hoga wo gpu ko support krega.

# Note: Google Collab pe pip ke jrurt ni hai. direct import ho jata hai.

# ....................//GPU VS CPU

In [ ]:
# +-----------------------------------------+-----------------------------------------------+
# | GPU (Graphics Processing Unit)          | CPU (Central Processing Unit)                 |
# | - A specialized processor designed for   | - The main processor in a computer that       |
# |   rendering graphics and performing      |   handles general-purpose tasks, executing    |
# |   parallel computations, such as deep   |   instructions and managing system resources. |
# |   learning operations.                   |                                               |
# +-----------------------------------------+-----------------------------------------------+
# | Less training time                      | High training time                            |
# |                                         | Because in TensorFlow, there are complex      |
# |                                         | mathematical calculations in the backend,     |
# |                                         | and the CPU is not optimized for such         |
# |                                         | operations.                                   |
# +-----------------------------------------+-----------------------------------------------+
# | Supports parallel computing             | Supports sequential computing                 |
# +-----------------------------------------+-----------------------------------------------+
# | Optimized for complex mathematical      | Can perform mathematical operations, but      |
# | operations (TensorFlow can utilize      | is not optimized for highly parallel tasks,   |
# | this for faster training)               | leading to slower training times              |
# +-----------------------------------------+-----------------------------------------------+
# | TensorFlow runs much faster on GPUs     | TensorFlow runs slower on CPUs                |
# | due to parallel processing              | due to limited parallelism capabilities       |
# +-----------------------------------------+-----------------------------------------------+
# | Designed for parallel computations      | Designed for general-purpose sequential tasks |
# | like rendering graphics and deep learning| such as logic operations and basic tasks      |
# +-----------------------------------------+-----------------------------------------------+


# ....................Install tensorflow using conda

In [ ]:
# All programs -> anacoda 64 -> Anaconda Promt (Anaconda 3)

# After opening this will apper in anaconda cmd -> (base) C:\Users\.. this is base environment.

# But hme base environment create nhi krna. If we want to create our own environment.
# then we will use below commands.


# For cpu version
# <------------------->

# 1. Conda create -n tf tensorflow <- create own base command
# 2. conda activate tf  <- install anaconda

# For GPU version
# <-------------------->
# Conda create -n tf-2-gpu tensorflow python=2
# conda activate tf-2-gpu


# we can also see these commands on anaconda documentation.

# ....................Import TensorFlow

In [ ]:
import tensorflow as tf

# tensorflow is package and tf is alias means short name/standard name

# 2) What is TensorFlow

In [ ]:
# In today's video we will talk about, Tensor + Flow
# what is Tensor? and
# what is Flow? and then both
# What is TensorFlow

# ....................Agenda

In [ ]:
# • Mathematical Foundation
# • What is Tensor?
# • What is Flow?
# • Study materials

# ....................Mathematical Foundation

In [ ]:
# Mathematical Foundation means not complete math pdhenge.
# but ise mathematical foundataion ke upar hi tensorflow ko build kiya hai.

In [ ]:
# • Scaler:
    # • Scalars are mathematical entities which have only a magnitude (and no direction)
    # • Ex: volume, density, speed, energy, mass, and time

# Vector:
    # • An array of numbers, which is either continuous or discrete, is defined as a vector.
    # • Ex: Force and velocity, have both magnitude and direction and are called vectors.

    # Directed line segment or ( magnitude+direction) is called vector. <- my 12th class defination.

# • Matrix:
#     • Matrix can be defined as multi-dimensional arrays, which are
#     • arranged in the format of rows and columns


In [ ]:
#           +----------+         +-----+       +--      --+
#  (11)     | 5 | 3 |7 |         |  5  |       | 4  19  8 |
#           +----------+         +-----+       | 16  3  5 |
#                                | 1.5 |       +--      --+
#                                +-----+
#                                |  2  |
#                                +-----+


# SCALAR      Row Vector         Column Vector      MATRIX
#             (shape 1x1)       (shape 3x1)

In [ ]:
# ....................What is TensorFlow?

In [ ]:
# TensorFlow = Tensor + Flow

# //1st we will talk about Tensor then Flow then Tensor?

In [ ]:
# ....................What is Tensor?

In [ ]:
# • Tensor:
#     • A tensor is a mathematical object
#     • Tensors are defined as multidimensional array or list.
#     • Tensors are identified by the following three parameters.
#       • Rank: It identifies the number of dimensions of the tensor
#           • Ex: Scalar, Vector, Matrix
#       • Shape: Number of rows and columns of Tensor
#       • Type: Data type assigned to Tensor's elements
#           • Ex: Integer, Float, String, boolean


# ..more points about tensor
#<------------------------>
# • Scalar, Arrays or vectors, which are one-dimensional, or matrices,
# which are two-dimensional. But tensors can be more than three,
# four or five dimensional.

# Tensor can be 0D, 1D,2D,3D,4D or multidimensions
# Means A Tensor in TensorFlow is an N-dimensional array.
# Tensors in TensorFlow are uniform, meaning that all the elements in a tensor must have the same data type and the same shape at each level.

![](https://miro.medium.com/v2/resize:fit:500/1*tD_RMFOOM17d7QENPhLy3w.png)

In [ ]:
# Above image at 06:10 in the video (dimensions of tensor flow)

In [ ]:
# Now, the question is arise that why we learn about tensors in deep learning?

# ans: when we work in dl then we have images and that images has different different shapes,
# and the data is in different format, and there also text data.
# So the shape of data is in different different format.
# and hm us data ke shape ke according model ko train krenge.
# so we learn tensor in dl and hmare pass jo data rhega wo used data rhega.
# and usko hme represent krna hai, usko shi treke utilize krna hai.

# ....................What is Flow of TensorFlow?

In [ ]:
# • Flow:
#     • Graphical representation of mathematical Operation
#     • Everything in TensorFLow is based on designing a computational graph.

#     • The graph has a network of nodes, with each node operating addition,
#     multiplication, or evaluating some multivariate equation.

#     • The code is written to build the graph, create a session, and execute that graph

    #  +----------+
    #  | Matrix A | \
    #  +----------+  _\/ +-----------+         +----------+
    #                __  | Add A & B |-------> |    C     |
    #  +----------+   /\ +-----------+         +----------+
    #  | Matrix B |  /
    #  +----------+

   # //input metrices/inputs  operations            output
  # //blue color box       yellow                  blue




# Expalantion:
#<------------->
# 1)
# Flow means graphical representation of mathematical operation.
# basically hm deep learning me kya krte hai. hm deep learning me
# mathematical operation perform krte hai.
# Deep learning me operation perform krne ke liye hm python code ka istemal
# krte to python code me hm kya krte?
# python code me hm TensorFlow framework ka istemal krte.
# To tensorflow me flow word means graphical representation of mathematical operation.

# So everything is tensorflow means jo bhi cheez hmare pass tensorflow me rhege,
# is a base on design a computational graph.

# To tensorflow me hm jb bhi coding krte hai.
# To hmare pass sbse pehle ek mathematical operation/formula rehta hai.
# hm us formula computational graph me represent krte hai.
# and uske badh me coding krte hai.

# so Flow means graphical representation of mathematical operation.
# and us graph ko dekhke hm coding krenge.
# and usko hm coding krenge TensorFlow me.



# 2nd point) nodes -> graph me nodes honge like matrix A & matrix B -> inme kuch mathematical operations honge -> and then hme output milega.

# 3rd point)
      # 1. Build the Graph:
      # First, you define the computation. This is like writing the blueprint or structure of what operations need to happen. You use TensorFlow operations (tf.Operation) to construct the graph, where nodes represent operations, and edges represent tensors flowing between them.
      # Example: You define variables, placeholders, and the operations that make up your neural network or mathematical computation. But at this stage, no computation happens yet.
      # 2. Create a Session:
      # Once the graph is built, you create a session using tf.Session() which acts as the environment to actually execute the operations you’ve defined in the graph.
      # The session holds and manages the state, resources, and computations required to run the graph.
      # 3. Execute the Graph:
      # After creating the session, you can now run the computations by using session.run(). Here, the graph is executed, meaning the operations you defined are computed, and the results are returned.

      # In short:
      # Code first defines the graph (blueprint of the operations).
      # Then, the session is created to execute the defined graph.
      # Finally, the graph is executed to get the results.

# Note: hm graph create krenge uske hisab se hm choose krenge ki kis dimension ka data lena hai.


# Note: hm jo mathematical operation perform krenge that code is already written in tensorflow so
# we just only call the api

# ....................What is TensorFlow?

In [ ]:
# • TensorFlow is the core open source library to help you develop and
# train Machine Learning/Deep Learning models.

# • Develop by Google Brain Team

# • TensorFlow is written in Python,C++,CUDA

# • Platform: Linux, macOS, Windows, Android, JavaScript

# • Initial release: November 9, 2015.

# ....................//what is Framework?
# ....................//Why TensorFlow is called Framework?

In [ ]:
# Framework: A framework provides a structure and pre-built tools for developing software efficiently.

# TensorFlow is a framework: because it offers pre-built tools and a structured approach for deep learning tasks.

# Pre-built Tools: TensorFlow provides ready-made functions for building and training machine learning models.
# Structure: It offers a defined way to organize and execute deep learning tasks (graph construction, session, etc.).


# 3) TensorFlow Programming Elements to build Tensors

# ....................Agenda

In [ ]:
# • Constant
# • Variable
# • Placeholder
# • Sparce Tensor

# ....................Programming Elements

In [ ]:
# //If we want to use tensorflow then we will have to create tensors.
# //So, there are following programming elements that we can use to create tensors:
# • Constant
# • Variable
# • Placeholder
# • Sparce Tensor

# ....................Constant

In [ ]:
# • Creates a constant tensor form a tensor-like object.

# Syntax: tf.constant()

# //imp Note: In constant -> we can not make changes after creating tensor.

# ....................Variable

In [ ]:
# • Variables allow us to add new trainable parameters to the graph

# Syntax: tf.variable()

# //Note: In Variable -> we can make changes after creating tensor.
# //tf.variable(value,datatype)

# ....................Placeholder

In [ ]:
# • Placeholder allow us to feed data to a TensorFLow model from outside a model

# Syntax: tf.placeholder()

# //Placeholder means if we are creating tensor,
# we can create tensor without inserting value in the tensor.
# Only mention the datatype of that tensor.
# this tensor is called placeholder.//

# ....................Sparse Tensor

In [ ]:
# • Sparse Tensor enable efficient storage and processing of tensors that
# contain a lot of zero values.

# Syntax: tf.SparsseTensor()


# if we want to create a tensor in which maximul value is zero.
# so that we can fulfil our operation then we will create sparsh tensor.

In [ ]:
# //This is theory discussion of the elements.
# //In the coming video. -> practical implementation.

# 4) Create Constant Tensor using TensorFlow 2.0 Python Tutorial

In [ ]:
# we use tensorflow to train dl neural network.

# To us time hmare pass kuch constant data rehta hai, jisko hm change ni krte hai while training.
# like user input.

# In this video we will talk about how to create
# 0d,1d,2d,3d,ND contant tensor

In [ ]:
# practice code
# from array import*
# a = array('i',[1,2,3,4,"a"])
# print(a)
# type(a)

# TypeError: 'str' object cannot be interpreted as an integer
# it means array must be of same data type.
# we know that array are hetegeneous

# ....................Constant

In [ ]:

# • Creates a constant tensor form a tensor-like object.

# Syntax: tf.constant()

# //imp Note: In constant -> we can not make changes after creating tensor.

In [ ]:
# ipynb -> interactive python notebook

# ....................How to Create Constant variable in TensorFlow 2.x

In [ ]:
# //version disscussion
#<----------------------->
# Upar heading me 2.x means 2 ke kitne bhi version aye like 2.1,2.10
# sbme suitable hai code hai, means code same hi rhega. to hm yha pe sikhenge.

# pehle tensorflow ka ek version that tensorflow 1.
# and iske popular version tha tensorflow1.14 and tensorflow 1.15
# ye versions aaj bhi use ho rha hai.

# //Important
#<-------------->
# But there are several differences between tensorflow 1 and tensorflow 2.
# tensorflow 2 is best in today's time.
# It has less lines of code.
# we can easily use keras in tensorflow 2.

In [ ]:
# tf.constant():

# Creates a constant tensor from a tensor-like object.

# # //There are 4 arguments of tensorflow.constant()//

# Args
# value   A constant value (or list) of output type dtype. //(int,float,str,bool)//
# shape   optional dimensions of resulting tensor.
# name    optional name for the tensor.

# Returns
# A Constant Tensor.

# REF: https://www.tensorflow.org/api_docs/python/tf/constant
# //REF means refer this is the official webite where we can
# know how tensorflow constant funtion works.//

# //Note: No need to define datatype. kuki code automaticaly jo bhi hm value di hogi like int
# to bhi tensor us particular element ka datatype define kr lega.

# Notes

In [ ]:
# 1. tf.Session() not in 2.x
# 2. Most of TensorFLow syntax same like Numpy

# 3. Use: While building neutral network graph need constant variable like input data,
#    it never change while training





# expalanation
# 1st point-> agr tensorflow 1 me graph create krne ke badh
# agr koi bhi variable hme dekhna hai. to sbse pehle hme usko execute krna pdta hai.
# Execute nhi krenge to hm usko access nhi kr payenge.
# but tensorflow 2 me hme ko session create nhi krna.

# 2.//bs hm numpy me np ka use krte the and tensorflow me tf ka use krenge.

# 3. use of contant variable -> hmare pass mathematical formula rehta hai.
# usko hm convert krte hai graph me -> and us graph ko hme actually program me convert krna
# pdta hai tb hm use krte hai tensorflow library ka.

# to tensorflow library me jb hm user ko input dete hai.
# then input value kuch na kuch rhege for example image data, text data or a number.
# to hm koi na koi data neural network ko pass krenge.
# agr hm neural network ko koi data pass krenge to wo constant rhega.
# wo training ke time pe input same rhega, change nhi hoga. but only output change hoga.

# In simple training ke time pe agr hm chahte hai ki hmara input fix rhe change na ho.
# bs output change ho. then we can use constant data.

In [ ]:
# Import TensorFlow

In [ ]:
import tensorflow as tf

# alias means short name
# tf is standard name/ globally used name/ short name.

# import is used to use package in python.

In [ ]:
# TensorFlow Version

In [ ]:
tf.__version__
# Note: version should be 2 and can anything in point.

'2.17.0'

In [ ]:
# Check GPU availability

In [ ]:
tf.test.is_gpu_available()

# GPU must be of nvidia for the True.
# mere laptop me amd ka gpu hai.but yha True nhi ayega. bcoz this is not nvidia.

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [ ]:
# Create Integer Constant

In [ ]:
# tf.constant()
# to shorcut for ctrl + shift + tab

In [ ]:
a = tf.constant(10)
a
# dtype is by defaul in the output

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
# Create Float Constant

In [ ]:
b = tf.constant(10.2)
b

<tf.Tensor: shape=(), dtype=float32, numpy=10.2>

In [ ]:
# Create String Constant

In [ ]:
c = tf.constant("Indian Ai Production")
c

<tf.Tensor: shape=(), dtype=string, numpy=b'Indian Ai Production'>

In [ ]:
# Create Bool Constant

In [ ]:
d = tf.constant(True)
d

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Create Constant Numpy array / list / Tuple
# // Create Constant tensor using numpy array

In [ ]:
import numpy as np

In [ ]:
np_array = tf.constant(np.array([1,2,3,4]))
np_array
# shape=(4,) it means 1d array

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [ ]:
# Create 1D constant

In [ ]:
t_1d = tf.constant([1,2,3,4])
t_1d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
# Create 2D constant

In [ ]:


t_2d = tf.constant([[1,2],[3,4]])
t_2d
# //This is 2d constant tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
t_2d_1 = tf.constant([1,2,3,4], shape=(2,2))
t_2d_1
# Note: The shape value product should be equal to the no. of elements.
# shape manually bhi de skte hai ese. manually means according to himself.

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
t_2d_1 = tf.constant([1,2,3,4], shape=(2,2), dtype="int32")
t_2d_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
t_2d_1 = tf.constant([1,2,3,4], shape=(2,2), dtype="float32")
t_2d_1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
# Create N-D constant

In [ ]:
t_3d_1 = tf.constant([[[1,2],[2,3],[4,5]]], dtype="float32")
t_3d_1
# 3 sq brackets means 3d tensor

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [2., 3.],
        [4., 5.]]], dtype=float32)>

In [ ]:
# Type of Constant

In [ ]:
type(t_3d_1)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
# Shape of Constant

In [ ]:
t_3d_1.shape
# TensorShape([1, 3, 2]) number of matrices ,row,col

TensorShape([1, 3, 2])

In [ ]:
t_2d.shape
# TensorShape([2, 2]) row,col

TensorShape([2, 2])

In [ ]:
# Access constant value

In [ ]:
t_1d.numpy()

# <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>
# upar ke codes me ye sb aa rha tha. but if we want to only array values.
# then we can use this code.

array([1, 2, 3, 4], dtype=int32)

In [ ]:
t_1d.numpy()[2]

3

In [ ]:
# constant dtype

In [ ]:
#// To check elements data type
t_3d_1.dtype

tf.float32

In [ ]:
# In this way we can use tf.constat() function to create tensors.

In [ ]:
# we can't give mixed value in tensorfow constant
# it gives an error
#<------------------------------------------------------->

# tf.constant([1,23.4,"Indian"])
# ValueError: Can't convert Python sequence with mixed types to Tensor.

# 5) Create TensorFlow Variable using TensorFlow 2.0

In [ ]:
# • Variables allow us to add new trainable parameters to the tf.Graph

# Syntax: tf.Variable() #// V capital

# //Here, graph means neural network structure.

# How to Create variable in TensorFlow 2.x

In [ ]:
# The Variable() constructor requires an initial value for the variable, which can be a Tensor of any
# type and shape. This initial value defines the type and shape of the variable. After construction,
# the type and shape of the variable are fixed. The value can be changed using one of the assign
# methods.

# Note: In constant we can't change values after creation.
# but in variable we can change.

In [ ]:
# //parameters

# tf.Variable(
#     initial_value=Noen, trainable=None, validate_shape=True, caching_device=None,
#     name=None, variable_def=None, dtype=None, import_scope=None, constraint=None,
#     sychronization=tf.VariablesSynchronization.AUTO,
#     aggregation=tf.compat.v1.VariableAggregation.NONE, shape=None
# )

# Import TensorFlow

In [ ]:
import tensorflow as tf

# Create Tensor

In [ ]:
tf.Variable(1)

# 0D (zero-dimensional): It has just a single value (a scalar), and no axes or dimensions.

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [ ]:
# integer value
a = tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
a.name

'Variable:0'

In [ ]:
a.shape

TensorShape([4])

In [ ]:
a.dtype

tf.int32

In [ ]:
# accessing variable values
a.numpy()

array([1, 2, 3, 4], dtype=int32)

In [ ]:
type(a)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

# Create TF using Integer, Float, String, Bool, Complex Number

In [ ]:
# float value
t_f = tf.Variable([1.2,4.4,5,6])
t_f

# t_f means tensorflow underscore float

# Note: if any value is float then it considered as float32

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([1.2, 4.4, 5. , 6. ], dtype=float32)>

In [ ]:
# string value
t_s = tf.Variable(['a','b','c','d'])
t_s

<tf.Variable 'Variable:0' shape=(4,) dtype=string, numpy=array([b'a', b'b', b'c', b'd'], dtype=object)>

In [ ]:
# boolean value
t_b = tf.Variable([True, False])
t_b

<tf.Variable 'Variable:0' shape=(2,) dtype=bool, numpy=array([ True, False])>

In [ ]:
# complex number
t_cx = tf.Variable([3 + 4j])
t_cx

<tf.Variable 'Variable:0' shape=(1,) dtype=complex128, numpy=array([3.+4.j])>

In [ ]:
# mycode 1
import numpy as np
a = np.array([1,2,3,4,5.5])
a.dtype
# datatype means element type

dtype('float64')

In [ ]:
# mycode2
type(a)
# type means kon si library hai.

numpy.ndarray

# Create TF from Constant TensorFlow to Variable

In [ ]:
t_con = tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

# My codes 1.1,1.2,2.1,2.2

# see diff. b/w var and con




In [ ]:
# 1.1) con to var (ok)
#<-------------------------->
t_con = tf.constant([1,2,3,4])
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
# 1.2) var to con (error)
#<------------------------->
# t_Var=tf.Variable([1,2,3,4])
# tf.consant(t_Var)

# it gives an error

In [ ]:
# code 2.1) changing var value (ok)
#<------------------------------------->

var = tf.Variable([10, 20, 30], dtype=tf.int32)
print("Initial value of variable x:", var.numpy())

var.assign([100, 200, 300])
print("Updated value of variable x:", var.numpy())


# var.numpy -> give only the array means only value

Initial value of variable x: [10 20 30]
Updated value of variable x: [100 200 300]


In [ ]:
# code 2.2) changing con value (error)
#<-------------------------------------->
# Create a TensorFlow Constant
con = tf.constant([10, 20, 30], dtype=tf.int32)
print("Value of constant y:", con.numpy())

# Uncommenting the following line will cause an error because constants can't be changed
# y.assign([100, 200, 300])  # This will cause an error

Value of constant y: [10 20 30]


# Create TF Variable with different shape

In [ ]:
t_2d = tf.Variable([[2,3], [4,5]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
t_2d_2 = tf.Variable([[2,3], [4,5]], shape=(2,2), dtype='float32')
t_2d_2

# Note: <tf.Variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

#### reshape

In [ ]:
# reshape
a = tf.Variable([1,2,3,4])
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
# reshape
tf.reshape(a, (2,2))

# Note: <tf.Tensor: but upar t_2d_2 wale me tf.Variable hai

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

# Get Index of highest value

In [ ]:
t_2d_2

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [ ]:
tf.argmax(t_2d_2)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [ ]:
tf.argmax(t_2d_2).numpy()

# Note: Index start from zero '0'

array([1, 1])

# Viewed/convert as a tensor

In [ ]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.convert_to_tensor(a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.convert_to_tensor(t_2d_2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

# Change/Assign new value to tensor

In [ ]:
# we can't change SHAPE AND DATA TYPE of variable but
# we can change value of variable
# YE HM IS VIDEO KE STARTING ME LIKHA HAI

In [ ]:
# Note: when we assing new value then wo value bhi same memory location pe
# store hota hai jha pehle wala tha.

# for ex: see below code
# a old value
# a ko hmne new value assign kr diya.
# to new wale value a ke hi location pe jake store hoga.

# In simple assign/new value store at the same memory location where the previous one.

In [ ]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([10, 20, 30, 40], dtype=int32)>

In [ ]:
a.assign([10,20,30,40])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([10, 20, 30, 40], dtype=int32)>

In [ ]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([10, 20, 30, 40], dtype=int32)>

# Assign Variable with another memory

In [ ]:
a.assign_add([4,6,2,8])
# This value stored at different memory location.
# not at 'a' location

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([14, 26, 32, 48], dtype=int32)>

# can't change shape and Data Type

In [ ]:
a

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([14, 26, 32, 48], dtype=int32)>

In [ ]:
# trying to change shape
#<------------------------------>
#  a.assign([4,6,2,8,7])


#  Shape mismatch.
#  The variable shape (4,),
#  assigned value shape (5,) are incompatible.

In [ ]:
# can't change data type of variable tensor
#<------------------------------------------->
# a.assign([4.2,6.7,2.0,8.1])

# TypeError: Cannot convert [4.2, 6.7, 2.0, 8.1] to EagerTensor of dtype int32

In [ ]:
# Note: gpu me parallel operation/work/task hota hai. it has high speed.
# cpu gives slow speed to train dl/neural network model.

# 6) Create TensorFlow Placeholder using TensorFlow 2.X

## How to Create placeholder in TensorFlow 2

# How to Migrate your TensorFlow 1 code to TensorFlow 2

In [ ]:
# //Note: tensor flow 2.X version version me tensorflow placeholder available nhi hai.
# 2.x means 2 ka koi sa bhi version point me.
# but we can use placeholder in tensorflow 2.
# but it is not the part of tensorflow 2.

# So we will discuss about how to migrate your tensorflow 1 code to tensorflow 2
# it means we tensorflow 1 me likhe hue code ko agr hme tensorflow 2 me use krna
# hai to kaise krenge.//

# Placeholder

In [ ]:
# A placeholder is simply a variable that we will assing data to at a later date. It allows us to create our operations and build our
# computation graph, without needing the data.

# Syntax: tf.compat.v1.placeholder(dtype, shape=None, name=None)

# import Tensorflow 2

In [ ]:
import tensorflow as tf

In [ ]:
# placeholders are not executable immediately so we need to disable eager execution in TF 2 not in 1


# explanation
#<------------>

# jb bhi hm placeholder use krna chahite hai tensorflow 2 me,
# tb hme disable eager execution krna pdta hai.

# jb bhi hm placeholder ko execute krenge tensorflow 1 me,
# to wha pe tensorflow 1 ko pta hai ki hme is particular variable ko
# execute abhi nhi krna hai, hme sirf uska graph create krna hai.
# but tensorflow 2 me esa nhi hota, usko nhi pta chlta hai ki is variable ko kb execute krna hai.
# means tensorflow 2 me jb hm placeholder create krenge to tensorflow 2 use immediately execute krega.
# jisse hme ek error milega

In [ ]:
# tf.compat.v1 <- it means tensorflow 1 me jo bhi function hai usko hme use krna hai tensorflow 2 me.
                    # v1 means version 1 se access krna hai.

# Create Placeholder

In [ ]:
# This is how to create placeholder in tensorflow 1
# but we are using tf 2 so it gives an error.
#<------------------------------------------------------->

# code
# tf.placeholder(dtype=tf.float32, shape=(400, 400))

# AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [ ]:
# code
# tf.compat.v1.placeholder(dtype=tf.float32, shape=(400, 400))

# RuntimeError: tf.placeholder() is not compatible with eager execution.

# it means -> tensorflow 2 me hm koi bhi variable ko access krte hai, to wo immediately execute hota hai.
# but hme use immediately execute ni krna hai, jb hm chahte hai tb execute ho.
# to hm disable eager execution ka use krenge.
# iss tf.placeholder() compatible ho jayega eager execution se.
# see below code

In [ ]:
#### first run disable command the and below cell command(placeholder command)

In [ ]:
# starting disable_eager_execution()
tf.compat.v1.disable_eager_execution()

In [ ]:
# tf.compat.v1 -> it is used to call the tensorflow 1 version function in tensorlow 2
#<---------------------------------------------------------------------------------------------->
a = tf.compat.v1.placeholder(dtype=tf.float32, shape=(400,400))
a

# yha pe koi bhi value ni hai, bcoz hm place holder ko bs shape and datatype btate hai.
# default dtype is float 32

<tf.Tensor 'Placeholder_4:0' shape=(400, 400) dtype=float32>

In [ ]:
a.dtype

tf.float32

In [ ]:
a.shape

TensorShape([400, 400])

In [ ]:
a.name

'Placeholder_4:0'

In [ ]:
b = tf.compat.v1.placeholder(dtype=tf.float32, shape=(400,400))
b

<tf.Tensor 'Placeholder_3:0' shape=(400, 400) dtype=float32>

# Perform mathematical operation with placeholder

In [ ]:
# adding 2 tensorflow placeholder
c = tf.add(a,b)
c

# analysis
#<------------>
# > abhi hmne sirf a and b code ka ek graph create kiya hai.
# > graph create ka mtlb ek structure bs create ho gya hai.ki iska ye shape hai, ye dtype hai and so on.
# > hmne abi code ko execute nhi kiya hai. To code ko execute krne ke liye hmare pass kuch data hona chahiye.
# we can take data from list or numpy array. see below 👇

<tf.Tensor 'Add:0' shape=(400, 400) dtype=float32>

# Create Numpy Array

In [ ]:
import numpy as np

In [ ]:
ones_array = np.ones((400,400), np.float32)
ones_array

# imp:
# now we will assign this data to our placeholder(a & b).
# and then we will execute mathematical operation. which is c

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

# Execute Tensorflow Placeholder using session

In [ ]:
with tf.compat.v1.Session() as sess:
  d = sess.run(c, feed_dict={a:ones_array, b:ones_array})

# code explanation
#<------------------->

# session() -> session 1 me hme koi bhi cheez execute krne hai to,
# uske liye hm session() ka use krte hai.

# tf.compat.v1.Session() -> version1 se hm session ko access krenge.

# sess.run() -> means hm jo bhi chez is function me dalenge wo run hoga tensorflow 1 me.



#### c, feed_dict={a:ones_array, b:ones_array}:

#  >  c -> means c ko execute krna hai.
#     c means operation ki variable me available hai uska varible ka name.

#  > feed_dict ->   c ko execute krne ke liye hme kuch data chahiye.
#     but a and b has no data. bcoz a and b is placeholder.
#     so we will feed/give data to a and b placeholder.

# > operation perform each and element wise.


In [ ]:
type(d)

# Note1: jb bhi hm session me koi bhi operation run krenge
# then we will get its type numpy array not tensorflow tensor.

# Note2: Now hm ye d variable ko kisis bhi tensorflow variable ya constant ko assign kr skte hai.

numpy.ndarray

In [ ]:
# Note: we will not use placeholder in tensorflow 2
# but this is for understanding what is placeholder and how to use it.

# 7) Create Sparse Tensor using TensorFlow 2.0

# Sparse Tensor

In [ ]:


# //inshort me ye hme smj aa gya defination
# //now in this today video we will do practical implemenatation

# data storage Unit

![](https://o.quizlet.com/wTQ3tPxI71AnHocqX23abA.png)

# 8) Create Ones vs Ones_like vs Ones_initializer Tensor using TensorFlow 2.0

In [ ]:
# A tensor with each and every element is one is called an "ones tensor"."

# How to create Tensor with every element are one in TensorFlow 2.x

# import TensorFlow 2

In [ ]:
import tensorflow as tf

# tf.ones()

Creates a tensor with all elements set to one (1).

In [ ]:
# 1d tensor
tf.ones((1), tf.float32)
# Note: not need to write dtype. bydefault it gives float32

# array ([[1., 1.],
        #  1., 1.]]), output esa ayega but show ni ho rha ye.

<tf.Tensor 'ones_3:0' shape=(1,) dtype=float32>

In [ ]:
# Ones 2d tensor
ones_2dt = tf.ones((2,2), tf.float32)
ones_2dt

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
ones_3dt = tf.ones((2,2,4), tf.float32)
ones_3dt

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [ ]:
import tensorflow as tf

ones_3dt = tf.ones((2, 2, 4), tf.float32)
print(ones_3dt.np())  # Yeh array ko display karega


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'np'

In [ ]:
import numpy as np
import tensorflow as tf